#!/bin/bash

PATH_TO_FILES="$(pwd)/$(dirname "$0")/pre-commit.d/*"

for hook in $PATH_TO_FILES; do
    bash $hook
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
        exit $RESULT
    fi
done

exit 0